title: Mejiro Philharmonic Orchestra
description: >-
  東京都豊島区を拠点に活動する、大学の垣根を超えた新たな形の学生主体のアマチュアオーケストラ。2018年結成。
twitter_username: MPOsince2018
facebook_username: MPOsince2018
theme: minima
plugins:
  - jekyll-feed
